# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20171022_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
