# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chicken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasty', models.CharField(max_length=30)),
            ],
        ),
    ]
