# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_application_rating'),
        ('portal', '0004_merge_20171029_2035'),
    ]

    operations = [
    ]
