# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='Chicken',
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
