# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField()),
                ('published', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='form',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portal.Form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='form',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portal.Form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='form',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portal.Form'),
            preserve_default=False,
        ),
    ]
