# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 02:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20180105_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='application',
            field=models.ForeignKey(db_column='application', on_delete=django.db.models.deletion.CASCADE, to='portal.Application'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(db_column='question', on_delete=django.db.models.deletion.CASCADE, to='portal.Question'),
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Category'),
        ),
        migrations.AlterField(
            model_name='application',
            name='form',
            field=models.ForeignKey(db_column='form', on_delete=django.db.models.deletion.CASCADE, to='portal.Form'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='applicant',
            field=models.ForeignKey(db_column='application', on_delete=django.db.models.deletion.CASCADE, to='portal.Application'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='exec_user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='form',
            field=models.ForeignKey(db_column='form', on_delete=django.db.models.deletion.CASCADE, to='portal.Form'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='applicant',
            field=models.ForeignKey(db_column='application', on_delete=django.db.models.deletion.CASCADE, to='portal.Application'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='form',
            field=models.ForeignKey(db_column='form', on_delete=django.db.models.deletion.CASCADE, to='portal.Form'),
        ),
    ]
