export const CHANGE_PATH = 'CHANGE_PATH';
export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';

export const REQUEST_PAGE = 'REQUEST_PAGE';
export const RECEIVE_PAGE = 'RECEIVE_PAGE';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';

export const RECEIVE_FORMS = 'RECEIVE_FORMS';
export const UPDATE_FORM = 'UPDATE_FORM';

export const SET_READ_STATUS = 'SET_READ_STATUS';

export const UPDATE_QUESTION = 'UPDATE_QUESTION';
