export const CHANGE_PATH = "CHANGE_PATH";
export const CHANGE_IS_MOBILE = "CHANGE_IS_MOBILE";
export const CHANGE_WIDTH_AND_HEIGHT = "CHANGE_WIDTH_AND_HEIGHT";
export const CHANGE_CURRENT_FORM_ID = "CHANGE_CURRENT_FORM_ID";

export const RECEIVE_FORMS = "RECEIVE_FORMS";
export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";
